version: "3"
services:
  postgres:
    container_name: nestjs-kysely-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - postgres
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env

  pgadmin:
    container_name: nestjs-kysely-pgadmin
    image: dpage/pgadmin4
    restart: always
    networks:
      - postgres
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    ports:
      - "5050:80"

networks:
  postgres:
    driver: bridge

